on: workflow_dispatch
jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Compile style.css from style.scss
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: assets/css/style.scss
          destination: assets/css/style.scss
